[package]
name = "abtestbed"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_rapier2d = { version = "0.28", features = [ "enhanced-determinism", "debug-render-2d" ] }
rand = "0.8.5"
uuid = { version = "1.3", features = ["v4"] }
mio = { version = "1.0.3" }
